// Definitions for game objects

#define obj_player     0
#define obj_killme     1
#define obj_heroswim   2
#define obj_herobee    3
#define obj_mine    	  4
#define obj_tiny       5
#define obj_text6      6
#define obj_text8      7
#define obj_bridger    8
#define obj_door       9
#define obj_centexpl   10
#define obj_addstep    11
#define obj_pad        12
#define obj_spring     13
#define obj_arrow      14
#define obj_masher     15
#define obj_platform   16
#define obj_checkpt    17
#define obj_elev       18
#define obj_mapdemo    19
#define obj_key        20
#define obj_heart      21
#define obj_emerald    22
#define obj_eagle      23
#define obj_epic       24
#define obj_grunt      25
#define obj_box        26
#define obj_score      27
#define obj_token      28
#define obj_switch     29
#define obj_button     30
#define obj_poker      31
#define obj_bullet     32
#define obj_bonus      33
#define obj_rock       34
#define obj_fireball   35
#define obj_laser      36
#define obj_torpedo    37
#define obj_fragexpl   38
#define obj_fireexpl   39
#define obj_flash      40
#define obj_hitwall    41
#define obj_gems       42
#define obj_spear      43
#define obj_stalag     44
#define obj_boulder    45
#define obj_ball       46
#define obj_fire       47
#define obj_searock    48
#define obj_torch      49
#define obj_biter      50
#define obj_cloud      51
#define obj_centipede  52
#define obj_alien      53
#define obj_leech      54
#define obj_troll      55
#define obj_blob       56
#define obj_hithero    57
#define obj_lizard     58
#define obj_spikes     59
#define obj_xargbot    60
#define obj_transport  61
#define obj_tmrpad     62
#define obj_effects    63
#define obj_krusty     64
#define obj_ghoul      65
#define obj_bubble     66
#define obj_eel        67
#define obj_badfish    68
#define obj_bat        69
#define obj_hopper     70
#define obj_txtmsg     71
#define obj_front      72
#define obj_timerpad   73
#define obj_turret     74
#define obj_creeper    75
#define obj_bee        77
#define obj_climber    78
#define obj_spider     79
#define obj_skull	     80
#define obj_seamonster 81
#define obj_robot      82
#define obj_redfish    83
#define obj_icons      84
#define obj_story1     85
#define obj_story2     86
#define obj_xargon     87
#define obj_map        88

#define numobjkinds    89